#ifndef _CAL_UI_H_
#define _CAL_UI_H_

// mostly generated by ai as it's just a ui front
#include <functional>

#include <QApplication>
#include <QHBoxLayout>
#include <QLineEdit>
#include <QList>
#include <QObject>
#include <QPushButton>
#include <QVBoxLayout>
#include <QWidget>
#include <qobjectdefs.h>

namespace vastina {

class Calculator : public QWidget {
    Q_OBJECT
  protected:
    QLineEdit *display;
    QList<QPushButton *> buttons;

    QString *res_;
    bool res_playing_{false};

  public:
    explicit Calculator(QWidget *parent = nullptr);
    ~Calculator();
  private slots:
    void digitClicked();
    void additiveClicked();
    void subtractiveClicked();
    void multiplicativeClicked();
    void divideClicked();
    void clear();
    void assignClicked();

  protected:
    void updater(const std::function<void()> &);
    void docalculate(const QString &);
    // QPushButton *createButton(const QString &, const std::function<void()>&);
};

}; // namespace vastina

#endif